//
//  ValidWordsExamples.swift
//  Letter Wall
//
//  Example words that will be accepted by the UK English dictionary
//

/*
 VALID 4-LETTER WORDS (Sample)
 ==============================
 
 Common words:
 - ABLE, BACK, CALL, CAME, COME, CARE, CASE, COAT, DARK, DATE
 - DOOR, EACH, EASY, FACE, FACT, FAIR, FALL, FAST, FEAR, FEEL
 - FELT, FILL, FIND, FINE, FIRE, FISH, FIVE, FLOW, FOOD, FOOT
 - FORM, FOUR, FREE, FROM, FULL, GAVE, GIRL, GIVE, GLAD, GOLD
 - GONE, GOOD, GREY, GROW, HALF, HALL, HAND, HARD, HAVE, HEAD
 - HEAR, HEAT, HELD, HELP, HERE, HIGH, HOLD, HOME, HOPE, HOUR
 - IDEA, INTO, IRON, JUST, KEEP, KEPT, KIND, KING, KNEW, KNOW
 - LADY, LAND, LAST, LATE, LEAD, LEFT, LESS, LIFE, LIKE, LINE
 - LIVE, LONG, LOOK, LOST, LOVE, MADE, MAIN, MAKE, MANY, MARK
 - MEAN, MEET, MILE, MIND, MISS, MORE, MOST, MOVE, MUCH, MUST
 - NAME, NEAR, NEED, NEXT, NICE, NOSE, NOTE, ONCE, ONLY, OPEN
 - OVER, PAGE, PAID, PAIR, PART, PASS, PAST, PATH, PLAN, PLAY
 - POOR, PULL, PUSH, RACE, RAIN, RANG, RATE, READ, REAL, REST
 - RIDE, RING, RISE, ROAD, ROCK, ROLE, ROLL, ROOM, ROSE, RULE
 - SAFE, SAID, SALE, SAME, SAVE, SEAT, SEEM, SEEN, SELF, SELL
 - SEND, SENT, SHIP, SHOP, SHOT, SHOW, SHUT, SIDE, SIGN, SING
 - SIZE, SLOW, SNOW, SOFT, SOLD, SOME, SONG, SOON, SORT, SPOT
 - STAR, STAY, STEP, STOP, SUCH, SURE, TAKE, TALK, TALL, TEAM
 - TELL, TERM, TEST, THAN, THAT, THEM, THEN, THEY, THIS, TIME
 - TOLD, TOOK, TOWN, TREE, TRUE, TURN, TYPE, UNIT, UPON, USED
 - VERY, VIEW, WAIT, WALK, WALL, WANT, WARM, WASH, WAVE, WEAK
 - WEAR, WEEK, WELL, WENT, WERE, WEST, WHAT, WHEN, WIDE, WIFE
 - WILL, WIND, WIRE, WISE, WISH, WITH, WOOD, WORD, WORE, WORK
 - YEAR, YOUR
 
 UK SPECIFIC 4-LETTER WORDS:
 - GREY (not gray)
 - TYRE (not tire)
 - KERB (not curb)
 
 VALID 5-LETTER WORDS (Sample)
 ==============================
 
 Common words:
 - ABOUT, ABOVE, ADDED, AFTER, AGAIN, AGREE, ALLOW, ALONE, ALONG
 - AMONG, ANGRY, APART, APPLY, AREAS, ARISE, ASKED, AVOID, BASED
 - BASIC, BEGAN, BEGIN, BEING, BELOW, BOARD, BREAK, BRING, BROWN
 - BUILD, BUILT, CAUSE, CHAIR, CHEAP, CHECK, CHIEF, CHILD, CHOSE
 - CIVIL, CLAIM, CLASS, CLEAN, CLEAR, CLOSE, COULD, COUNT, COVER
 - CROSS, DAILY, DEATH, DOING, DOUBT, DRAWN, DREAM, DRESS, DRIVE
 - DROVE, EARLY, EARTH, EIGHT, ENJOY, ENTER, EQUAL, ERROR, EVENT
 - EVERY, EXACT, EXIST, EXTRA, FACTS, FIELD, FIFTY, FIGHT, FINAL
 - FIRST, FLOOR, FORCE, FORTH, FORTY, FOUND, FRESH, FRONT, FULLY
 - GIVEN, GLASS, GOING, GRACE, GRAND, GRANT, GRASS, GREAT, GREEN
 - GROUND, GROUP, GUESS, HAPPY, HEARD, HEART, HEAVY, HENRY, HORSE
 - HOUSE, HUMAN, IDEAL, IMAGE, INDEX, ISSUE, JAMES, JONES, JUDGE
 - KNOWN, LARGE, LATER, LAUGH, LEARN, LEAST, LEAVE, LEGAL, LEVEL
 - LIGHT, LIMIT, LINES, LIVED, LOCAL, LOOSE, LOUIS, LOVED, LOWER
 - MAGIC, MAJOR, MAKES, MARCH, MATCH, MAYBE, MEANT, METAL, MIGHT
 - MINOR, MONEY, MONTH, MORAL, MOTOR, MOUNT, MOUTH, MOVED, MUSIC
 - NEEDS, NEVER, NEWLY, NIGHT, NOISE, NORTH, NOTED, NOVEL, OCCUR
 - OFFER, OFTEN, ORDER, OTHER, OUGHT, OWNED, PARTY, PEACE, PETER
 - PHONE, PLACE, PLAIN, PLANE, PLANT, PLATE, POINT, POUND, POWER
 - PRESS, PRICE, PRIDE, PRIME, PRINT, PRIOR, PROVE, QUEEN, QUICK
 - QUIET, QUITE, RADIO, RAISE, RANGE, REACH, READY, REFER, RIGHT
 - RIVER, ROMAN, ROUGH, ROUND, ROUTE, ROYAL, SCALE, SCENE, SCOPE
 - SCORE, SENSE, SERVE, SEVEN, SHALL, SHAPE, SHARE, SHEET, SHIFT
 - SHINE, SHIRT, SHOCK, SHOOT, SHORT, SHOWN, SIDES, SIGHT, SINCE
 - SIXTH, SIXTY, SIZED, SKILL, SLAVE, SLEEP, SMALL, SMILE, SMITH
 - SOLID, SOLVE, SORRY, SOUND, SOUTH, SPACE, SPARE, SPEAK, SPEED
 - SPEND, SPENT, SPLIT, SPOKE, SPORT, STAFF, STAGE, STAND, START
 - STATE, STEAM, STEEL, STICK, STILL, STOCK, STONE, STOOD, STORE
 - STORM, STORY, STRIP, STUDY, STUFF, STYLE, SUGAR, SWEET, TABLE
 - TAKEN, TASTE, TEACH, TERMS, THANK, THEIR, THEME, THERE, THESE
 - THICK, THING, THINK, THIRD, THOSE, THREE, THREW, THROW, TIGHT
 - TIMES, TITLE, TODAY, TOPIC, TOTAL, TOUCH, TOUGH, TOWER, TRACK
 - TRADE, TRAIN, TREAT, TREND, TRIAL, TRIED, TRIES, TROOP, TRULY
 - TRUST, TRUTH, TWICE, UNDER, UNION, UNITY, UNTIL, UPPER, URBAN
 - USAGE, USUAL, UTTER, VALID, VALUE, VIDEO, VISIT, VITAL, VOICE
 - WASTE, WATCH, WATER, WHEEL, WHERE, WHICH, WHILE, WHITE, WHOLE
 - WHOSE, WOMAN, WOMEN, WORLD, WORRY, WORSE, WORST, WORTH, WOULD
 - WRITE, WRONG, WROTE, YOUNG, YOUTH
 
 UK SPECIFIC 5+ LETTER WORDS:
 - COLOUR, FAVOUR, HONOUR, LABOUR, NEIGHBOUR, RUMOUR, BEHAVIOUR
 - CENTRE, METRE, LITRE, THEATRE, FIBRE
 - ANALYSE, APOLOGISE, ORGANISE, REALISE, RECOGNISE
 - DEFENCE, LICENCE, OFFENCE, PRETENCE
 - PROGRAMME, CHEQUE
 
 TIPS FOR FINDING WORDS:
 =======================
 
 1. Look for common letter patterns:
    - ING endings (but need 4+ letters: RING, SING, WING, KING, TING)
    - ED endings (AGED, USED, NEED, FEED, SEED)
    - ER endings (EVER, OVER, TIER, BEER, DEER, SEER)
    - LY endings (ONLY, HOLY, UGLY, JULY)
    - TH combinations (THAT, THEN, THIS, THEM, WITH, BOTH)
 
 2. Common prefixes:
    - OVER- (OVER, OVERTIME, OVERHEAD)
    - UNDER- (UNDER, UNDERSTAND, UNDERGROUND)
    - RE- (READ, REAL, RENT, REST, RECALL)
 
 3. Vowel-consonant patterns:
    - Look for words with multiple vowels
    - A-E-I-O-U combinations
 
 4. Double letters:
    - BEEN, SEEN, KEEP, FEEL, MEET, BOOK, LOOK, FOOD, GOOD
    - MISS, BOSS, PASS, LESS, FULL, TELL, WELL
 
 5. Common word families:
    - TIME, TIMER, TIMED (but TIMER and TIMED are 5 letters)
    - MAKE, MADE, MAKER (MAKE/MADE are 4, MAKER is 5)
    - PLAY, PLAYS, PLAYED, PLAYER (check lengths!)
 
 STRATEGY:
 =========
 
 - Longer words score more (10 points per letter)
 - Look for 6+ letter words for maximum points
 - Common UK spellings give you advantage
 - Adjacent/diagonal tiles give you flexibility
 - Plan ahead for cascading letters
 
 */
